global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s
  external_labels:
    monitor: devnetcreate

rule_files:
- "rules.d/*.rule"

scrape_configs:
- job_name: example_app
  honor_labels: true
  basic_auth:
    username: metrics
    password: metrics
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ['python:9090']
