global:
  scrape_interval: 5s
  external_labels:
    monitor: devnetcreate

scrape_configs:
  - job_name: python_app
    honor_labels: true
    static_configs:
      - targets: ['python_app:9091']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
