{
 "title": "Cluster Health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "content": "graph LR\nez-dash_python_app --> ez-dash_influxdb\nez-dash_python_app --> ez-dash_prometheus\nez-dash_metricbeat --> ez-dash_elasticsearch\nez-dash_elasticsearch --> ez-dash_grafana\nez-dash_elasticsearch --> ez-dash_kibana\nez-dash_influxdb --> ez-dash_grafana\nez-dash_prometheus --> ez-dash_grafana\n\n",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker.container.labels.com_docker_swarm_service_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "docker.memory.usage.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:docker AND metricset.name:memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "content": "graph LR\nez-dash_python_app --> ez-dash_influxdb\nez-dash_python_app --> ez-dash_prometheus\nez-dash_metricbeat --> ez-dash_elasticsearch\nez-dash_elasticsearch --> ez-dash_grafana\nez-dash_elasticsearch --> ez-dash_kibana\nez-dash_influxdb --> ez-dash_grafana\nez-dash_prometheus --> ez-dash_grafana\n\n",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker.container.labels.com_docker_swarm_service_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "docker.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.module:docker AND metricset.name:cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{term docker.container.labels.com_docker_swarm_service_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker.container.labels.com_docker_swarm_service_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "docker.memory.usage.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:docker AND metricset.name:memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker.container.labels.com_docker_swarm_service_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "docker.cpu.total.pct",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:docker AND metricset.name:cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "{{term docker.container.labels.com_docker_swarm_service_name}} IN",
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker.container.labels.com_docker_swarm_service_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "docker.network.in.bytes",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricset.module:docker AND metricset.name:network",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term docker.container.labels.com_docker_swarm_service_name}} OUT",
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker.container.labels.com_docker_swarm_service_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker.network.out.bytes",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}