metricbeat.max_start_delay: 0s
max_procs: 1
tags: ["DevNetCreate"]
setup.kibana.host: "kibana:5601"
setup.dashboards.enabled: true
metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 5s
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
